services:
  db:
    image: postgres:15-alpine
    container_name: aracyonetimi_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: AsbPassword123
      POSTGRES_DB: AracYonetimiDb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata: