// <auto-generated />
using System;
using AracYonetimi.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AracYonetimi.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260714111500_IlkKurulum")]
    partial class IlkKurulum
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AracYonetimi.Core.Entities.Arac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<bool>("BakimBildirim")
                        .HasColumnType("boolean");

                    b.Property<int?>("BakimOransalSinir")
                        .HasColumnType("integer");

                    b.Property<int?>("BakimPeriyot")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedByModule")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUser")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DemirbasKod")
                        .HasColumnType("text");

                    b.Property<string>("DepartmanKod")
                        .HasColumnType("text");

                    b.Property<string>("DovizKod")
                        .HasColumnType("text");

                    b.Property<string>("DurumKod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirmaKod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("IlkKmSaat")
                        .HasColumnType("numeric");

                    b.Property<bool>("Iptal")
                        .HasColumnType("boolean");

                    b.Property<bool>("KmSaatKontrol")
                        .HasColumnType("boolean");

                    b.Property<int?>("KmSaatSinir")
                        .HasColumnType("integer");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MarkaKod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("MevcutKmSaat")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Onay")
                        .HasColumnType("boolean");

                    b.Property<string>("PersonelAdSoyad")
                        .HasColumnType("text");

                    b.Property<string>("PersonelKod")
                        .HasColumnType("text");

                    b.Property<string>("Plaka")
                        .HasColumnType("text");

                    b.Property<string>("SahipFirmaKod")
                        .HasColumnType("text");

                    b.Property<string>("Seri")
                        .HasColumnType("text");

                    b.Property<string>("SorumluKod")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SozlesmeBaslangicTarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SozlesmeBitisTarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SozlesmeIptalTarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TahsisTipKod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TesisKod")
                        .HasColumnType("text");

                    b.Property<string>("TipKod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Tutar")
                        .HasColumnType("numeric");

                    b.Property<string>("UpdatedByModule")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedByUser")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VitesTip")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("arac", (string)null);
                });

            modelBuilder.Entity("AracYonetimi.Core.Entities.AracDurum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DurumAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tanim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Kod")
                        .IsUnique();

                    b.ToTable("AracDurumlar");
                });

            modelBuilder.Entity("AracYonetimi.Core.Entities.AracMarka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MarkaAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tanim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Kod")
                        .IsUnique();

                    b.ToTable("AracMarkalar");
                });

            modelBuilder.Entity("AracYonetimi.Core.Entities.AracTahsisTip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TahsisTipAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tanim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Kod")
                        .IsUnique();

                    b.ToTable("AracTahsisTipler");
                });

            modelBuilder.Entity("AracYonetimi.Core.Entities.AracTip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tanim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Kod")
                        .IsUnique();

                    b.ToTable("AracTipler");
                });

            modelBuilder.Entity("AracYonetimi.Core.Entities.Doviz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DovizCinsi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tanim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Kod")
                        .IsUnique();

                    b.ToTable("Dovizler");
                });

            modelBuilder.Entity("AracYonetimi.Core.Entities.Firma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirmaAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Kod")
                        .IsUnique();

                    b.ToTable("Firmalar");
                });

            modelBuilder.Entity("AracYonetimi.Core.Entities.Personel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirmaKod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Kod")
                        .IsUnique();

                    b.ToTable("Personeller");
                });
#pragma warning restore 612, 618
        }
    }
}
